// Generated by CoffeeScript 1.7.1

/*
	Copyright 2014 David Pearson.
	All rights reserved.
 */

(function() {
  var matchTeam, natural, teams;

  natural = require("natural");

  teams = {
    "Buffalo Bills": ["bills"],
    "Miami Dolphins": ["dolphins", "fins"],
    "New England Patriots": ["patriots", "pats"],
    "New York Jets": ["jets", "gang green"],
    "Baltimore Ravens": ["ravens"],
    "Cincinnati Bengals": ["bengals"],
    "Cleveland Browns": ["browns"],
    "Pittsburgh Steelers": ["steelers", "stillers", "stihllers"],
    "Houston Texans": ["texans"],
    "Indianapolis Colts": ["colts"],
    "Jacksonville Jaguars": ["jaguars", "jags"],
    "Tennessee Titans": ["titans"],
    "Denver Broncos": ["broncos"],
    "Kansas City Chiefs": ["chiefs"],
    "Oakland Raiders": ["raiders", "silver and black"],
    "San Diego Chargers": ["chargers", "bolts"],
    "Dallas Cowboys": ["cowboys", "boys", "americas team"],
    "New York Giants": ["giants", "big blue", "gmen"],
    "Washington Redskins": ["redskins", "skins"],
    "Chicago Bears": ["bears"],
    "Detroit Lions": ["lions"],
    "Green Bay Packers": ["packers", "pack", "green and gold"],
    "Minnesota Vikings": ["vikings", "vikes"],
    "Atlanta Falcons": ["falcons"],
    "Carolina Panthers": ["panthers"],
    "New Orleans Saints": ["saints"],
    "Tampa Bay Buccaneers": ["buccaneers", "bucs"],
    "Arizona Cardinals": ["cardinals", "cards"],
    "St. Louis Rams": ["rams"],
    "San Francisco 49ers": ["49ers", "niners"],
    "Seattle Seahawks": ["seahawks", "hawks"]
  };

  matchTeam = function(str) {
    var bestMatch, bestScore, nickname, score, team, word, words, _i, _j, _len, _len1, _ref;
    if (typeof str !== "string") {
      return "";
    }
    words = str.toLowerCase().split(" ");
    bestMatch = "";
    bestScore = 0.0;
    for (team in teams) {
      _ref = teams[team];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        nickname = _ref[_i];
        for (_j = 0, _len1 = words.length; _j < _len1; _j++) {
          word = words[_j];
          score = natural.JaroWinklerDistance(word, nickname);
          if (score > bestScore) {
            bestMatch = team;
            bestScore = score;
          }
        }
      }
    }
    return bestMatch;
  };

  exports.matchTeam = matchTeam;

}).call(this);
